#!/bin/bash

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
#
# This sample shows how to prevent push of commits where the log message starts
# with "WIP" (work in progress).

if ! hash astyle; then
	echo "You do not have astyle installed so your code style is not being checked!"
	exit 0
fi

cargo fmt --version >/dev/null 2>&1
if [[ $? != 0 ]]; then
	echo "Warning: \`cargo fmt\` is not available."
	exit 0
fi

info=$(make format-check)
if [ -n "$info" ]; then
	echo "Format Error detected:"
	echo
	echo "$info"
	echo
	echo "To get rid of the format warnings above, please run \`make format\` before next commit."
	echo
	exit 1
fi

exit 0
