version: 2

# Set the version of Python
build:
  os: ubuntu-22.04  # <- add this line
  tools:
    python: "3.10"

sphinx:
  configuration: docs/readthedocs/docs/source/conf.py

python:
  install:
    - requirements: docs/readthedocs/requirements.txt

formats:
  - pdf
