ARG OCCLUM_VERSION
FROM occlum/occlum:$OCCLUM_VERSION-ubuntu20.04 as base
LABEL maintainer="Chunyang Hui <sanqian.hcy@antgroup.com>"

ARG OCCLUM_BRANCH
WORKDIR /root
RUN rm -rf /root/demos && \
    git clone -b $OCCLUM_BRANCH https://github.com/occlum/occlum.git && \
    cp -r occlum/demos /root/demos && \
    rm -rf /root/occlum

WORKDIR /root/demos/openvino
RUN bash -x install_cmake.sh && \
    bash -x download_and_build_openvino.sh && \
    bash -x download_openvino_model.sh

WORKDIR /root
