ARG OCCLUM_VERSION
FROM jessehui/occlum:occlum-ubuntu20.04-edmm-experiment-v6 as base
LABEL maintainer="He Sun <bochang.sh@antgroup.com>"

# Install gvisor syscall test binaries
WORKDIR /root
RUN git clone -b occlum-release-20200921.0 https://github.com/occlum/gvisor.git && \
    cd gvisor/occlum && \
    ./prepare_bazel.sh && \
    ./build_and_install_syscall_tests.sh && \
    cd /root && \
    mv gvisor/occlum gvisor_occlum && \
    rm -rf gvisor

WORKDIR /root
