ARG OCCLUM_VERSION
FROM occlum/occlum:$OCCLUM_VERSION-ubuntu18.04 as base
LABEL maintainer="Chunyang Hui <sanqian.hcy@antgroup.com>"

WORKDIR /root
RUN git clone https://github.com/occlum/occlum.git && \
    cp -r occlum/demos /root/demos && \
    rm -rf /root/occlum

WORKDIR /root/demos/openvino
RUN bash -x install_cmake.sh && \
    bash -x download_and_build_openvino.sh && \
    bash -x download_openvino_model.sh

WORKDIR /root
