[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Occlum"
authors = [{name = "Qi Zheng", email = "huaiqing.zq@antgroup.com"}]
dynamic = ["version", "description"]
