#! /usr/bin/fish
command /usr/lib/jvm/java-11-openjdk-amd64/bin/java \
        -Xmx800m -XX:-UseCompressedOops -XX:MaxMetaspaceSize=256m -XX:ActiveProcessorCount=2 \
        -Dos.name=Linux \
        -Dlog.file=$log \
        -Dlog4j.configuration=file:/bin/conf/log4j.properties \
        -Dlog4j.configurationFile=file:/bin/conf/log4j.properties \
        -Dlogback.configurationFile=file:/bin/conf/logback.xml \
        -classpath /bin/lib/flink-table-blink_2.11-1.10.1.jar:/bin/lib/flink-table_2.11-1.10.1.jar:/bin/lib/log4j-1.2.17.jar:/bin/lib/slf4j-log4j12-1.7.15.jar:/bin/lib/flink-dist_2.11-1.10.1.jar org.apache.flink.client.cli.CliFrontend \
        $argv