[package]
name = "init"
version = "0.0.1"
authors = ["LI Qing geding.lq@antgroup.com"]
edition = "2018"

[dependencies]
libc = "0.2.84"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.9"
sha2 = "0.9.5"
reqwest = { version = "0.11", features = ["blocking", "json"] }
occlum_dcap = { path = "../../../../../tools/toolchains/dcap_lib" }

